import type { Category, Product } from '@/types/pos';

/**
 * Fallback menu data - used when database is unavailable
 * Your actual menu should be stored in Supabase database
 * Run supabase/migrations/001_menu.sql to seed the database
 */
export const CATS: Category[] = [
  { id: 'all', name: 'ทั้งหมด', color: '#f5a623' },
  { id: 'krapow', name: 'กระเพรา', color: '#ef4444' },
  { id: 'curry', name: 'เครื่องแกง', color: '#f97316' },
  { id: 'stir', name: 'ผัดต่างๆ', color: '#eab308' },
  { id: 'rice', name: 'ข้าวผัด/ราดหน้า', color: '#22c55e' },
  { id: 'somtam', name: 'ส้มตำ/ยำ', color: '#06b6d4' },
  { id: 'soup', name: 'แกงส้ม/ต้ม', color: '#8b5cf6' },
  { id: 'seafood', name: 'ทะเล/ปลา', color: '#3b82f6' },
  { id: 'special', name: 'พิเศษ', color: '#ec4899' },
  { id: 'side', name: 'ของเพิ่ม', color: '#6b7280' },
];

export const MENU: Product[] = [
  { id: 1, name: 'กระเพราทะเล + ไข่ดาว', cat: 'krapow', price: 80 },
  { id: 2, name: 'กระเพราหมู/ไก่ + ไข่ดาว', cat: 'krapow', price: 70 },
  { id: 3, name: 'กระเพราหมูกรอบ + ไข่ดาว', cat: 'krapow', price: 80 },
  { id: 4, name: 'เครื่องแกงทะเล + ไข่ดาว', cat: 'curry', price: 80 },
  { id: 5, name: 'เครื่องแกงหมูกรอบ + ไข่ดาว', cat: 'curry', price: 80 },
  { id: 6, name: 'เครื่องแกงหมู/ไก่ + ไข่ดาว', cat: 'curry', price: 70 },
  { id: 7, name: 'เครื่องแกงกุ้งสะตอ + ไข่ดาว', cat: 'curry', price: 120 },
  { id: 8, name: 'เครื่องแกงหมูสะตอ + ไข่ดาว', cat: 'curry', price: 100 },
  { id: 9, name: 'คะน้าหมูกรอบ + ไข่ดาว', cat: 'stir', price: 80 },
  { id: 10, name: 'ผัดพริกทะเล + ไข่ดาว', cat: 'stir', price: 80 },
  { id: 11, name: 'ผัดพริกหมู/ไก่ + ไข่ดาว', cat: 'stir', price: 70 },
  { id: 12, name: 'ทะเลผัดน้ำพริกเผา + ไข่ดาว', cat: 'stir', price: 80 },
  { id: 13, name: 'หมู/ไก่ผัดน้ำพริกเผา + ไข่ดาว', cat: 'stir', price: 70 },
  { id: 14, name: 'ผักกูดผัดไฟแดงหมูกรอบ', cat: 'stir', price: 150 },
  { id: 15, name: 'หมึกหอมผัดกะปิสะตอ', cat: 'stir', price: 450 },
  { id: 16, name: 'กุ้งผัดกะปิสะตอ', cat: 'stir', price: 250 },
  { id: 17, name: 'หมึกไข่ผัดน้ำดำ', cat: 'stir', price: 450 },
  { id: 18, name: 'ปลากะพงผัดฉ่า', cat: 'stir', price: 250 },
  { id: 19, name: 'ทะเลกระเทียมพริกไทย', cat: 'stir', price: 250 },
  { id: 20, name: 'ทะเลผัดผงกะหรี่', cat: 'stir', price: 250 },
  { id: 21, name: 'คะน้าหมูกรอบ', cat: 'stir', price: 150 },
  { id: 22, name: 'ใบเหลียงผัดไข่', cat: 'stir', price: 100 },
  { id: 23, name: 'ข้าวผัดทะเล', cat: 'rice', price: 80 },
  { id: 24, name: 'ข้าวผัดหมู/ไก่', cat: 'rice', price: 70 },
  { id: 25, name: 'ราดหน้า หมู/ไก่/ทะเล', cat: 'rice', price: 80 },
  { id: 26, name: 'ผัดซีอิ๊ว หมู/ไก่', cat: 'rice', price: 70 },
  { id: 27, name: 'ส้มตำปู ปลาร้า', cat: 'somtam', price: 80 },
  { id: 28, name: 'ส้มตำไทย', cat: 'somtam', price: 60 },
  { id: 29, name: 'ส้มตำข้าวโพดไข่เค็ม', cat: 'somtam', price: 80 },
  { id: 30, name: 'ส้มตำปู ปลาร้า กุ้งสด', cat: 'somtam', price: 120 },
  { id: 31, name: 'ยำไข่เยี่ยวม้า', cat: 'somtam', price: 120 },
  { id: 32, name: 'ยำทะเล', cat: 'somtam', price: 120 },
  { id: 33, name: 'ยำวุ้นเส้นทะเล', cat: 'somtam', price: 120 },
  { id: 34, name: 'ลาบหมู', cat: 'somtam', price: 120 },
  { id: 35, name: 'แกงส้มกุ้งมังคุดคัด', cat: 'soup', price: 250 },
  { id: 36, name: 'แกงส้มปลากะพงทุเรียน', cat: 'soup', price: 250 },
  { id: 37, name: 'แกงส้มกุ้งชะอมไข่', cat: 'soup', price: 200 },
  { id: 38, name: 'แกงส้มปลาหมึกไข่', cat: 'soup', price: 250 },
  { id: 39, name: 'ต้มจืดเต้าหู้หมูสับ', cat: 'soup', price: 100 },
  { id: 40, name: 'ต้มยำทะเลหม้อไฟ', cat: 'soup', price: 250 },
  { id: 41, name: 'ปลากะพงทอดน้ำปลา', cat: 'seafood', price: 350 },
  { id: 42, name: 'หมึกไข่ต้มน้ำดำสูตรชาวเล', cat: 'seafood', price: 250 },
  { id: 43, name: 'กุ้งแชบ๊วยซอสมะขาม', cat: 'seafood', price: 450 },
  { id: 44, name: 'ปลาหมึกไข่นึ่งมะนาว', cat: 'seafood', price: 250 },
  { id: 45, name: 'ปลากะพงผัดฉ่า', cat: 'seafood', price: 250 },
  { id: 46, name: 'ปลาหมึกนึ่งมะนาว', cat: 'seafood', price: 250 },
  { id: 47, name: 'ไก่ทอด', cat: 'special', price: 80 },
  { id: 48, name: 'หมูสามชั้นทอด', cat: 'special', price: 120 },
  { id: 49, name: 'เฟรนฟราย', cat: 'special', price: 80 },
  { id: 50, name: 'ข้าวเปล่า (จาน)', cat: 'side', price: 20 },
  { id: 51, name: 'ข้าวเปล่า (โถ)', cat: 'side', price: 60 },
];
