-- Phase 2: Menu in DB
-- Run this in Supabase Dashboard → SQL Editor → New query, then Run.

-- Categories (id is string e.g. 'krapow')
CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '#6b7280',
  sort_order INT NOT NULL DEFAULT 0
);

-- Products
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id TEXT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order INT NOT NULL DEFAULT 0
);

-- RLS: only authenticated users can read/write (single-tenant)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "categories_authenticated_all" ON categories;
CREATE POLICY "categories_authenticated_all" ON categories
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "products_authenticated_all" ON products;
CREATE POLICY "products_authenticated_all" ON products
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Seed categories (exclude 'all' – that's UI-only)
INSERT INTO categories (id, name, color, sort_order) VALUES
  ('krapow', 'กระเพรา', '#ef4444', 1),
  ('curry', 'เครื่องแกง', '#f97316', 2),
  ('stir', 'ผัดต่างๆ', '#eab308', 3),
  ('rice', 'ข้าวผัด/ราดหน้า', '#22c55e', 4),
  ('somtam', 'ส้มตำ/ยำ', '#06b6d4', 5),
  ('soup', 'แกงส้ม/ต้ม', '#8b5cf6', 6),
  ('seafood', 'ทะเล/ปลา', '#3b82f6', 7),
  ('special', 'พิเศษ', '#ec4899', 8),
  ('side', 'ของเพิ่ม', '#6b7280', 9)
ON CONFLICT (id) DO NOTHING;

-- Seed products (same order as MENU in constants.ts so ids match)
INSERT INTO products (id, category_id, name, price, sort_order) OVERRIDING SYSTEM VALUE VALUES
  (1, 'krapow', 'กระเพราทะเล + ไข่ดาว', 80, 1),
  (2, 'krapow', 'กระเพราหมู/ไก่ + ไข่ดาว', 70, 2),
  (3, 'krapow', 'กระเพราหมูกรอบ + ไข่ดาว', 80, 3),
  (4, 'curry', 'เครื่องแกงทะเล + ไข่ดาว', 80, 1),
  (5, 'curry', 'เครื่องแกงหมูกรอบ + ไข่ดาว', 80, 2),
  (6, 'curry', 'เครื่องแกงหมู/ไก่ + ไข่ดาว', 70, 3),
  (7, 'curry', 'เครื่องแกงกุ้งสะตอ + ไข่ดาว', 120, 4),
  (8, 'curry', 'เครื่องแกงหมูสะตอ + ไข่ดาว', 100, 5),
  (9, 'stir', 'คะน้าหมูกรอบ + ไข่ดาว', 80, 1),
  (10, 'stir', 'ผัดพริกทะเล + ไข่ดาว', 80, 2),
  (11, 'stir', 'ผัดพริกหมู/ไก่ + ไข่ดาว', 70, 3),
  (12, 'stir', 'ทะเลผัดน้ำพริกเผา + ไข่ดาว', 80, 4),
  (13, 'stir', 'หมู/ไก่ผัดน้ำพริกเผา + ไข่ดาว', 70, 5),
  (14, 'stir', 'ผักกูดผัดไฟแดงหมูกรอบ', 150, 6),
  (15, 'stir', 'หมึกหอมผัดกะปิสะตอ', 450, 7),
  (16, 'stir', 'กุ้งผัดกะปิสะตอ', 250, 8),
  (17, 'stir', 'หมึกไข่ผัดน้ำดำ', 450, 9),
  (18, 'stir', 'ปลากะพงผัดฉ่า', 250, 10),
  (19, 'stir', 'ทะเลกระเทียมพริกไทย', 250, 11),
  (20, 'stir', 'ทะเลผัดผงกะหรี่', 250, 12),
  (21, 'stir', 'คะน้าหมูกรอบ', 150, 13),
  (22, 'stir', 'ใบเหลียงผัดไข่', 100, 14),
  (23, 'rice', 'ข้าวผัดทะเล', 80, 1),
  (24, 'rice', 'ข้าวผัดหมู/ไก่', 70, 2),
  (25, 'rice', 'ราดหน้า หมู/ไก่/ทะเล', 80, 3),
  (26, 'rice', 'ผัดซีอิ๊ว หมู/ไก่', 70, 4),
  (27, 'somtam', 'ส้มตำปู ปลาร้า', 80, 1),
  (28, 'somtam', 'ส้มตำไทย', 60, 2),
  (29, 'somtam', 'ส้มตำข้าวโพดไข่เค็ม', 80, 3),
  (30, 'somtam', 'ส้มตำปู ปลาร้า กุ้งสด', 120, 4),
  (31, 'somtam', 'ยำไข่เยี่ยวม้า', 120, 5),
  (32, 'somtam', 'ยำทะเล', 120, 6),
  (33, 'somtam', 'ยำวุ้นเส้นทะเล', 120, 7),
  (34, 'somtam', 'ลาบหมู', 120, 8),
  (35, 'soup', 'แกงส้มกุ้งมังคุดคัด', 250, 1),
  (36, 'soup', 'แกงส้มปลากะพงทุเรียน', 250, 2),
  (37, 'soup', 'แกงส้มกุ้งชะอมไข่', 200, 3),
  (38, 'soup', 'แกงส้มปลาหมึกไข่', 250, 4),
  (39, 'soup', 'ต้มจืดเต้าหู้หมูสับ', 100, 5),
  (40, 'soup', 'ต้มยำทะเลหม้อไฟ', 250, 6),
  (41, 'seafood', 'ปลากะพงทอดน้ำปลา', 350, 1),
  (42, 'seafood', 'หมึกไข่ต้มน้ำดำสูตรชาวเล', 250, 2),
  (43, 'seafood', 'กุ้งแชบ๊วยซอสมะขาม', 450, 3),
  (44, 'seafood', 'ปลาหมึกไข่นึ่งมะนาว', 250, 4),
  (45, 'seafood', 'ปลากะพงผัดฉ่า', 250, 5),
  (46, 'seafood', 'ปลาหมึกนึ่งมะนาว', 250, 6),
  (47, 'special', 'ไก่ทอด', 80, 1),
  (48, 'special', 'หมูสามชั้นทอด', 120, 2),
  (49, 'special', 'เฟรนฟราย', 80, 3),
  (50, 'side', 'ข้าวเปล่า (จาน)', 20, 1),
  (51, 'side', 'ข้าวเปล่า (โถ)', 60, 2)
ON CONFLICT (id) DO UPDATE SET
  category_id = EXCLUDED.category_id,
  name = EXCLUDED.name,
  price = EXCLUDED.price,
  sort_order = EXCLUDED.sort_order;

-- Optional: link order_items to products (if order_items table already exists)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'order_items') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'order_items' AND column_name = 'product_id') THEN
      ALTER TABLE order_items ADD COLUMN product_id BIGINT REFERENCES products(id);
    END IF;
  END IF;
END $$;
