-- Raw materials inventory: ingredients + recipe (product_ingredients) + movements
-- Run after 001_menu.sql (products) and 005_orders.sql (orders)

-- Raw materials (ingredients)
CREATE TABLE IF NOT EXISTS raw_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'g' CHECK (unit IN ('g', 'kg', 'pcs', 'ml')),
  stock_qty NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
  low_stock_threshold NUMERIC(12, 2) CHECK (low_stock_threshold IS NULL OR low_stock_threshold >= 0),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Recipe: which raw materials and how much per serving of a dish
CREATE TABLE IF NOT EXISTS product_ingredients (
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  raw_material_id BIGINT NOT NULL REFERENCES raw_materials(id) ON DELETE RESTRICT,
  quantity_per_serving NUMERIC(10, 2) NOT NULL CHECK (quantity_per_serving > 0),
  PRIMARY KEY (product_id, raw_material_id)
);

CREATE INDEX IF NOT EXISTS idx_product_ingredients_raw_material_id ON product_ingredients(raw_material_id);

-- Audit log for raw material stock changes
CREATE TABLE IF NOT EXISTS raw_material_movements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  raw_material_id BIGINT NOT NULL REFERENCES raw_materials(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('adjustment', 'sale', 'restock')),
  qty_delta NUMERIC(12, 2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  order_id UUID REFERENCES orders(id) ON DELETE SET NULL,
  note TEXT
);

CREATE INDEX IF NOT EXISTS idx_raw_material_movements_raw_material_id ON raw_material_movements(raw_material_id);
CREATE INDEX IF NOT EXISTS idx_raw_material_movements_created_at ON raw_material_movements(created_at DESC);

-- RLS
ALTER TABLE raw_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE raw_material_movements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "raw_materials_authenticated_all" ON raw_materials;
CREATE POLICY "raw_materials_authenticated_all" ON raw_materials
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "product_ingredients_authenticated_all" ON product_ingredients;
CREATE POLICY "product_ingredients_authenticated_all" ON product_ingredients
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "raw_material_movements_authenticated_all" ON raw_material_movements;
CREATE POLICY "raw_material_movements_authenticated_all" ON raw_material_movements
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Atomic: deduct raw material stock for an order. Raises if insufficient stock.
CREATE OR REPLACE FUNCTION decrement_raw_material_stock(p_order_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  r RECORD;
  v_required NUMERIC;
  v_current NUMERIC;
BEGIN
  -- Build required amount per raw_material from order_items + product_ingredients
  FOR r IN (
    SELECT
      pi.raw_material_id,
      SUM(pi.quantity_per_serving * oi.qty) AS total_required
    FROM order_items oi
    JOIN product_ingredients pi ON pi.product_id = oi.product_id
    WHERE oi.order_id = p_order_id
      AND oi.product_id IS NOT NULL
    GROUP BY pi.raw_material_id
  ) LOOP
    v_required := r.total_required;
    SELECT stock_qty INTO v_current FROM raw_materials WHERE id = r.raw_material_id;
    IF v_current IS NULL OR v_current < v_required THEN
      RAISE EXCEPTION 'Insufficient stock for raw material id %: has %, need %',
        r.raw_material_id, COALESCE(v_current, 0), v_required;
    END IF;
  END LOOP;

  -- Deduct and log
  FOR r IN (
    SELECT
      pi.raw_material_id,
      SUM(pi.quantity_per_serving * oi.qty) AS total_required
    FROM order_items oi
    JOIN product_ingredients pi ON pi.product_id = oi.product_id
    WHERE oi.order_id = p_order_id
      AND oi.product_id IS NOT NULL
    GROUP BY pi.raw_material_id
  ) LOOP
    UPDATE raw_materials
    SET stock_qty = stock_qty - r.total_required,
        updated_at = NOW()
    WHERE id = r.raw_material_id;

    INSERT INTO raw_material_movements (raw_material_id, type, qty_delta, order_id)
    VALUES (r.raw_material_id, 'sale', -r.total_required, p_order_id);
  END LOOP;
END;
$$;
